services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  publisher:
    build:
      context: ./publisher
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://mongo:27017/streets

  publisher-cli:
    build:
      context: ./cli
    # depends_on:
    #   - publisher
    environment:
      - API_HOST=http://publisher:3000

  consumer:
    build:
      context: ./consumer
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://mongo:27017/streets
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
  postgres:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: streetsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./line-string-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  line-string-service:
    build:
      context: ./line-string-service
    depends_on:
      - postgres
      - publisher
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=streetsdb
      - PUBLISHER_API=http://publisher:3000
    ports:
      - "4000:4000"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  mongo:
  redpanda:
  postgres_data:
networks:
  default:
    driver: bridge
    # prevent conflict with openVPN connection, use dedicated subnet
    ipam:
      config:
        - subnet: 172.16.57.0/24
