volumes:
  mongo:
  redpanda:
networks:
  default:
    driver: bridge
    # prevent conflict with openVPN connection, use dedicated subnet
    ipam:
      config:
        - subnet: 172.16.57.0/24
services:
  # The following services are not used in the current implementation:
  # - s2 (SingleStore)
  # - redpanda
  # - redpanda-ui
  # These can be removed or commented out if not needed for future use.

  # redpanda:
  #   image: docker.redpanda.com/vectorized/redpanda:latest
  #   command:
  #     - redpanda start
  #     - --smp 1
  #     - --memory 1G
  #     - --reserve-memory 0M
  #     - --overprovisioned
  #     - --node-id 0
  #     - --check=false
  #     - --pandaproxy-addr INSIDE://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
  #     - --advertise-pandaproxy-addr INSIDE://redpanda:28082,OUTSIDE://localhost:8082
  #     - --kafka-addr INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
  #     - --advertise-kafka-addr INSIDE://redpanda:29092,OUTSIDE://localhost:9092
  #     - --rpc-addr 0.0.0.0:33145
  #     - --advertise-rpc-addr redpanda:33145
  #   volumes:
  #     - redpanda:/var/lib/redpanda/data
  #   ports:
  #     - 8081:8081
  #     - 8082:8082
  #     - 9092:9092
  #     - 9644:9644
  # redpanda-ui:
  #   image: docker.redpanda.com/vectorized/console:latest
  #   entrypoint: /bin/sh
  #   command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
  #   environment:
  #     CONFIG_FILEPATH: /tmp/config.yml
  #     CONSOLE_CONFIG_FILE: |
  #       kafka:
  #         brokers: ["redpanda:29092"]
  #         schemaRegistry:
  #           enabled: false
  #           urls: ["http://redpanda:8081"]
  #       redpanda:
  #         adminApi:
  #           enabled: true
  #           urls: ["http://redpanda:9644"]
  #       connect:
  #         enabled: false
  #         clusters:
  #           - name: local-connect-cluster
  #             url: http://redpanda:8083
  #   ports:
  #     - 8014:8080
  #   depends_on:
  #     - redpanda
  # s2:
  #   image: memsql/cluster-in-a-box:latest
  #   environment:
  #     - LICENSE_KEY=BDA0ZmY4MjM5MGE1ZTRjODE5ZWI4ZmYyYTQ5MmYwMzNjAAAAAAAAAAAEAAAAAAAAAAwwNQIYDAszyc7y00icQmrwoFyBISxNyjKDn73vAhkA3bqahIUESIf3NOS71yjjpU1qC1nB7u2bAA==
  #     - ROOT_PASSWORD=Password1
  #     - START_AFTER_INIT=true
  #   restart: "always"
  #   ports: 
  #     - 3306:3306
  #     - 8012:8080
  mongo: 
    image: mongo:4.2
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongo:/data/db
  rabbitmq:
   image: rabbitmq:3-management
   restart: always
   ports:
     - 5672:5672
     - 15672:15672
  publisher:
    build:
      context: ./publisher
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://mongo:27017/streets

  publisher-cli:
    build:
      context: ./cli
    # depends_on:
    #   - publisher
    environment:
      - API_HOST=http://publisher:3000

  consumer:
    build:
      context: ./consumer
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - MONGO_URI=mongodb://mongo:27017/streets